provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  msg-payload-splitter:
    lang: java8
    handler: ./msg-payload-splitter
    image: ustmico/msg-payload-splitter:latest
    #annotations:
    #  topic: splitter-request
