version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  react-redux-transformer:
    lang: python3
    handler: ./react_redux_transformer
    image: ustmico/react-redux-transformer:latest
